# Generated by Django 5.0.6 on 2024-06-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Invitation Code')),
                ('expire', models.DateTimeField(verbose_name='Expire Time')),
            ],
        ),
    ]
